# Extra autostart processes
# exec-once = uwsm-app -- my-service

exec-once = hyprsession

# Communication apps
exec-once = [workspace 1 silent] slack
exec-once = [workspace 9 silent] discord
exec-once = [workspace 10 silent] signal-desktop

# Chrome profiles
exec-once = [workspace 2 silent] google-chrome-stable --profile-directory="Profile 2"
exec-once = [workspace 8 silent] google-chrome-stable --profile-directory="Default"
